import java.sql.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditData.java
 *
 * Created on 29 Oct, 2017, 12:07:32 AM
 */

/**
 *
 * @author User
 */
public class EditData extends javax.swing.JFrame {

    /** Creates new form EditData */
    public EditData() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTable1.setForeground(new java.awt.Color(255, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UID", "USERNAME", "PASSWORD", "NAME", "ADDRESS", "contact_no", "EMAIL", "NEED", "TYPE", "REGION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 280, 1270, 210);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("CLEAR TABLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1173, 243, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("ACT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 250, 80, 25);

        jList1.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 14));
        jList1.setForeground(new java.awt.Color(0, 102, 153));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "SELECT TYPE OF ACTION", "SEARCH", "DELETE", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(450, 90, 150, 100);

        jComboBox1.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 14));
        jComboBox1.setForeground(new java.awt.Color(0, 102, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CONDITION", "=", "like" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(770, 120, 100, 24);

        jComboBox2.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 14));
        jComboBox2.setForeground(new java.awt.Color(0, 102, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Column to be matched", "UID", "USERNAME", "PASSWORD", "NAME", "ADDRESS", "contact_no", "EMAIL", "NEED", "TYPE", "REGION" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(50, 130, 150, 30);

        jTextField1.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 14));
        jTextField1.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1010, 120, 130, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setForeground(new java.awt.Color(51, 102, 255));
        jButton2.setText("<= BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 100, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Log Out !");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1210, 0, 100, 23);

        jLabel2.setFont(new java.awt.Font("Gungsuh", 1, 18));
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("User Data (EDIT)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 10, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20171101191014.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1290, 500);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1306)/2, (screenSize.height-540)/2, 1306, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String action=(String) jList1.getSelectedValue();
String col=null,condition,val;
DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
col=(String) jComboBox2.getSelectedItem();
condition=(String)jComboBox1.getSelectedItem();
val=jTextField1.getText();
try{
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pukar","root","root");
Statement stmt=con.createStatement();
if(action.equals("SEARCH")){
String query="select * from users where "+col+" "+condition+"  '"+val+"';";
System.out.println(query);
ResultSet rs=stmt.executeQuery(query);
while(rs.next()){
            String a=rs.getString("UID");
            String b=rs.getString("USERNAME");
            String c=rs.getString("PASSWORD");
            String d=rs.getString("NAME");
            String e=rs.getString("ADDRESS");
            String f=rs.getString("contact_no");
            String g=rs.getString("EMAIL");
            String h=rs.getString("NEED");
            String i=rs.getString("TYPE");
            String j=rs.getString("REGION");
            tb.addRow(new Object[] {a,b,c,d,e,f,g,h,i,j});
}
rs.close();
}
else if(action.equals("DELETE")){
String query="delete from users where "+col+" "+condition+"  '"+val+"';";
int rs=stmt.executeUpdate(query);
}
stmt.close();
con.close();
}
catch (Exception e){
        System.out.println(e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 login a=new login();
a.setVisible(true);
this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
admincontrol a=new admincontrol();
a.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
int row=jTable1.getRowCount();
for(int i=1;i<=row;i++){
jTable1;
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
