import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pay.java
 *
 * Created on 28 Oct, 2017, 5:22:24 PM
 */

/**
 *
 * @author User
 */
public class pay extends javax.swing.JFrame {

    /** Creates new form pay */
    public pay() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Forte", 1, 19));
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("QuickPay");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 10, 120, 30);

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Aharoni", 0, 12));
        jRadioButton1.setForeground(new java.awt.Color(51, 0, 51));
        jRadioButton1.setText("MasterCard");
        jRadioButton1.setEnabled(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(700, 200, 120, 21);

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 15));
        jLabel2.setForeground(new java.awt.Color(102, 153, 0));
        jLabel2.setText("Select the Card Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(680, 160, 150, 30);

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Aharoni", 0, 12));
        jRadioButton2.setForeground(new java.awt.Color(51, 0, 51));
        jRadioButton2.setText("Rupay");
        jRadioButton2.setEnabled(false);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(700, 230, 100, 21);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Aharoni", 0, 12));
        jRadioButton3.setForeground(new java.awt.Color(51, 0, 51));
        jRadioButton3.setText("Visa");
        jRadioButton3.setEnabled(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(700, 260, 90, 21);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Aharoni", 0, 12));
        jRadioButton4.setForeground(new java.awt.Color(51, 0, 51));
        jRadioButton4.setText("Maestro");
        jRadioButton4.setEnabled(false);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(700, 290, 110, 21);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Yu Gothic Light", 1, 12));
        jRadioButton5.setText("DEBIT or CREDIT CARD");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(80, 190, 180, 29);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jRadioButton6.setText("Internet Banking");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(80, 370, 150, 29);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jRadioButton7.setText("QuickPay Wallet");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(80, 410, 150, 29);

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 15));
        jLabel3.setForeground(new java.awt.Color(102, 153, 0));
        jLabel3.setText("Payment Mode");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 140, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 460, 80, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Log Out !");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(827, 0, 100, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20171101190527.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 930, 490);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-945)/2, (screenSize.height-531)/2, 945, 531);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(jRadioButton5.isSelected()==true){
JOptionPane.showInputDialog("Input Card No.","");
JOptionPane.showInputDialog("Enter OTP","");
JOptionPane.showMessageDialog(null,"<html>Payment Succesfully Completed<br>Visit US Again :)");
}
else if (jRadioButton6.isSelected()==true){
    JOptionPane.showInputDialog("UserID","");
    JOptionPane.showInputDialog("ID Password","");
    JOptionPane.showMessageDialog(null,"<html>Payment Succesfully Completed<br>Visit US Again :)");
}
else{
    JOptionPane.showInputDialog("UserID","");
    JOptionPane.showInputDialog("Password","");
    JOptionPane.showMessageDialog(null,"<html>Payment Succesfully Completed<br>Visit US Again :)");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
jRadioButton1.setEnabled(true);
jRadioButton2.setEnabled(true);
jRadioButton3.setEnabled(true);
jRadioButton4.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
login a=new login();
a.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
jRadioButton1.setEnabled(false);
jRadioButton2.setEnabled(false);
jRadioButton3.setEnabled(false);
jRadioButton4.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
jRadioButton1.setEnabled(false);
jRadioButton2.setEnabled(false);
jRadioButton3.setEnabled(false);
jRadioButton4.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables

}
