import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * signup.java
 *
 * Created on Sep 27, 2017, 12:37:32 PM
 */

/**
 *
 * @author Abhinav
 */
public class signup extends javax.swing.JFrame {

    /** Creates new form signup */
    public signup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 17));
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Signup");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 4, 80, 30);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 14));
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 120, 100, 30);

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 14));
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("UID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 404, 70, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(344, 304, 180, 80);

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 14));
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 190, 90, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 0, 0);

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 14));
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 310, 90, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(410, 410, 100, 20);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(420, 120, 100, 21);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(410, 460, 100, 21);

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 14));
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 450, 80, 30);

        jLabel8.setFont(new java.awt.Font("Algerian", 0, 14));
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Contact No.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 260, 110, 30);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(420, 260, 100, 21);

        jLabel9.setFont(new java.awt.Font("Algerian", 0, 14));
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 510, 70, 30);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(350, 521, 160, 20);

        jButton1.setFont(new java.awt.Font("Andalus", 1, 16));
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 570, 100, 40);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(420, 180, 100, 21);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setForeground(new java.awt.Color(51, 153, 255));
        jButton2.setText("<= BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 90, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20171101191715.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 4, 570, 630);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 300, 2, 2);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-590)/2, (screenSize.height-675)/2, 590, 675);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int uid;
String user,pass,name,add,email,cont;
uid=Integer.parseInt(jTextField1.getText());
user=jTextField2.getText();
pass=new String(jPasswordField1.getPassword());
name=jTextField4.getText();
add=jTextArea1.getText();
cont=jTextField6.getText();
email=jTextField7.getText();
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pukar","root","root");
Statement stmt= con.createStatement();
String query="insert into users (uid,username,password,name,address,contact_no,email) values("+uid+",'"+user+"','"+pass+"','"+name+"','"+add+"','"+cont+"','"+email+"');";
System.out.print(query);
int rs= stmt.executeUpdate(query);
}catch(Exception e){
System.out.println(e);
}
JOptionPane.showMessageDialog(null,"New User Added");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
login a=new login();
a.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
