import java.sql.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * transport.java
 *
 * Created on 29 Oct, 2017, 12:08:55 AM
 */

/**
 *
 * @author User
 */
public class transport extends javax.swing.JFrame {

    /** Creates new form transport */
    public transport() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mode", "LoadingCapacity", "Destination", "GoodsType", "VehicleNo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 240, 950, 230);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("CLEAR TABLE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(840, 210, 110, 30);

        jLabel1.setFont(new java.awt.Font("DFKai-SB", 1, 16));
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("TRANSPORT CONTROL CENTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 10, 240, 30);

        jLabel2.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mode");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 74, 90, 20);

        jLabel3.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LoadingCapacity");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 104, 140, 20);

        jLabel4.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destination");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 144, 120, 20);

        jLabel5.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GoodsType");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 180, 120, 20);

        jLabel6.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VehicleNo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 214, 110, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(350, 80, 110, 20);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 110, 110, 20);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(350, 140, 110, 21);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(350, 180, 110, 21);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(350, 210, 110, 21);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 70, 80, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setText("CHECK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 120, 90, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 0));
        jButton3.setText("REMOVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 170, 100, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 0));
        jButton4.setText("CHANGE DESTINATION");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(560, 210, 170, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton5.setForeground(new java.awt.Color(0, 153, 255));
        jButton5.setText("<= BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(0, 0, 100, 25);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("Log Out !");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(837, 0, 110, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/23.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 950, 240);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-966)/2, (screenSize.height-511)/2, 966, 511);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String mode,load,dest,type,veh;
mode=jTextField1.getText();
load=jTextField2.getText();
dest=jTextField3.getText();
type=jTextField4.getText();
veh=jTextField5.getText();
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pukar","root","root");
Statement stmt= con.createStatement();
String query="insert into transport values('"+mode+"','"+load+"','"+dest+"','"+type+"','"+veh+"');";
System.out.print(query);
int rs= stmt.executeUpdate(query);
}catch(Exception e){
System.out.println(e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 String mode,load,dest,type,veh;
 DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
mode=jTextField1.getText();
load=jTextField2.getText();
dest=jTextField3.getText();
type=jTextField4.getText();
veh=jTextField5.getText();
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pukar","root","root");
Statement stmt= con.createStatement();
String query="select * from transport where mode='"+mode+"' or loadingcapacity='"+load+"' or destination='"+dest+"' or goodstype='"+type+"' or vehicleno='"+veh+"';";
System.out.print(query);
ResultSet rs= stmt.executeQuery(query);
while(rs.next()){
            String a=rs.getString("Mode");
            String b=rs.getString("LoadingCapacity");
            String c=rs.getString("Destination");
            String d=rs.getString("GoodsType");
            String e=rs.getString("VehicleNo");

            tb.addRow(new Object[] {a,b,c,d,e});
}

rs.close();
}catch(Exception e){
System.out.println(e);
}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String mode,load,dest,type,veh;
mode=jTextField1.getText();
load=jTextField2.getText();
dest=jTextField3.getText();
type=jTextField4.getText();
veh=jTextField5.getText();
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pukar","root","root");
Statement stmt= con.createStatement();
String query="delete from transport where mode='"+mode+"' or loadingcapacity='"+load+"' or destination='"+dest+"' or goodstype='"+type+"' or vehicleno='"+veh+"';";
System.out.print(query);
int rs= stmt.executeUpdate(query);
}catch(Exception e){
System.out.println(e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String mode,load,dest,type,veh;
mode=jTextField1.getText();
load=jTextField2.getText();
dest=jTextField3.getText();
type=jTextField4.getText();
veh=jTextField5.getText();
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pukar","root","root");
Statement stmt= con.createStatement();
String query="update transport set destination='"+dest+"' where mode='"+mode+"' or loadingcapacity='"+load+"' or destination='"+dest+"' or goodstype='"+type+"' or vehicleno='"+veh+"';";
System.out.println(query);
int rs= stmt.executeUpdate(query);
}catch(Exception e){
System.out.println(e);
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
login a=new login();
a.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
admincontrol a=new admincontrol();
a.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
int row=jTable1.getRowCount();
for(int i=1;i<=row;i++){
jTable1;
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
